config/routes.rb
Rails.application.routes.draw do
  get 'paplessso/top'
  get 'converts/download/:id',to: "converts#download",as: "download_file"
  resources :converts
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stem</title>
    <%= favicon_link_tag '/update_icon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>
  <% if flash[:alert] %>
    <div class = "flash text-center p-3 mb-2 bg-danger text-white">
      <%= flash[:alert] %>
    </div>
  <% end %> 
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/error.html.erb

<!doctype html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <title></title>
    </head>
    <body>
    
    <div class="row justify-content-center">   
        <span class="display-1">404</span>
    </div>
    <div class="row justify-content-center">   
        <p class="text-muted">Page Not Found</p>
    </div>
    <div class="container">
        <div class="row justify-content-center"> 
            <p class="text-muted">指定されたページまたはディレクトリが見つかりませんでした</p>
        </div>
        <div class="row justify-content-center"> 
            <p class="text-muted">もう一度最初からやり直してください</p>
        </div>
    </div>
    <div class="row justify-content-center"> 
        <%= link_to 'トップページへ戻る', converts_url %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.js"></script>
    <script>
        bsCustomFileInput.init();
    </script>
    </body>
</html>